# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='descriptions',
            field=models.TextField(default='my description default'),
        ),
    ]
